[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[window]
opacity = 0.8

[window.padding]
x = 8
y = 4

[keyboard]
