[local]
desktop ansible_connection=local ansible_user=conspicio aur_helper=yay
laptop  ansible_connection=local ansible_user=conspicio aur_helper=yay

[all:vars]
ansible_python_interpreter=/usr/bin/python3
